version: '3.8'

services:
  server:
    volumes:
      - ./server:/app:cached
      - ./core:/core:cached
  web:
    volumes:
      - ./web:/app:cached
      - ./core:/core:cached
    ports:
      - "5173:5173"
  client:
    privileged: true
    env_file:
      - ./.env
    build:
      context: ./client
      target: ${ENVIRONMENT}
    depends_on:
      - emqx
    networks:
      - emqx-bridge
      - srs
    ports:
      - "8888:8888"
    volumes:
      - ./client:/app:cached
    devices:
      - "/dev/video0:/dev/video0"
