name: main

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Test
        run: |
          echo "Test"