name: main

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/ubuntu/raspberrpi
            git fetch
            git reset --hard origin/main
            docker compose -f docker-compose.yml -f docker-compose.prod.yml build
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d