name: server

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'server/**'

jobs:
  lint:
    uses: ./.github/workflows/node-command.yml
    with:
      command: npm run lint:check
      working-directory: ./server
  prettier-check:
    uses: ./.github/workflows/node-command.yml
    with:
      command: npm run format:check
      working-directory: ./server