name: web

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'web/**'

jobs:
  lint:
    uses: ./.github/workflows/node-command.yml
    with:
      command: npm run lint-check
      working-directory: ./web
  prettier-check:
    uses: ./.github/workflows/node-command.yml
    with:
      command: npm run format-check
      working-directory: ./web
  type-check:
    uses: ./.github/workflows/node-command.yml
    with:
      command: npm run type-check
      working-directory: ./web